name: LorraineJug
description: Lorraine Java User Group
url: http://www.lorrainejug.org
exclude: [README.md, _site/, lorrainejug.github.io.iml]
markdown: redcarpet
highlighter: true
baseurl:
paginate: 5
paginate_path: events/:num
sass:
    sass_dir: css/_sass
    style: compressed             # nested|expanded|compact|compressed

