name: LorraineJug
description: Lorraine Java User Group
url: http://www.lorrainejug.org
exclude: [README.md, _site/, lorrainejug.github.io.iml]
gems: [jekyll-sass]
markdown: redcarpet
pygments: true
baseurl:
paginate: 5
paginate_path: events/:num
sass:
    style: compressed           # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: true   # true|false
